### ISSUE TITLE
Upgrading from jeffjirsa/TWCS to Cassandra TWCS

### ISSUE THREAD

**Issue by myoussefakamai** [jeffjirsa/twcs#9]
Currently using Cassanra 2.2.14 with jeffjirsa 2.2 branch of twcs. I converted a number of CFs to use com.jeffjirsa.cassandra.db.compaction.TimeWindowCompactionStrategy

Now I am upgrading the cluster to Cassandra 3.0.18. I am getting tons of errors using the jeffjirsa/twcs 3.0.0 jar. What's the proper way to migrate?

**Comment by myoussefakamai** [comment]
Failing with the below after upgrading one node in a 2.2.14 cluster to 3.0.18 and using any version of jeffjirsa/twcs:

`ERROR [CompactionExecutor:11] 2019-05-14 14:36:04,969 CassandraDaemon.java:207 - Exception in thread Thread[CompactionExecutor:11,1,main]
java.lang.NoSuchMethodError: org.apache.cassandra.db.ColumnFamilyStore.getOverlappingSSTables(Lorg/apache/cassandra/db/lifecycle/SSTableSet;Ljava/lang/Iterable;)Ljava/util/Collection;
	at com.jeffjirsa.cassandra.db.compaction.TimeWindowCompactionStrategy.getNextBackgroundSSTables(TimeWindowCompactionStrategy.java:110) ~[TimeWindowCompactionStrategy-3.3.jar:na]
	at com.jeffjirsa.cassandra.db.compaction.TimeWindowCompactionStrategy.getNextBackgroundTask(TimeWindowCompactionStrategy.java:79) ~[TimeWindowCompactionStrategy-3.3.jar:na]
	at org.apache.cassandra.db.compaction.CompactionStrategyManager.getNextBackgroundTask(CompactionStrategyManager.java:102) ~[apache-cassandra-3.0.18.jar:3.0.18]
	at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionCandidate.run(CompactionManager.java:257) ~[apache-cassandra-3.0.18.jar:3.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:79) [apache-cassandra-3.0.18.jar:3.0.18]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]`
